apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - image: ghcr.io/chneau/example-todo-aspnet-react:latest
          name: demo
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "75Mi"
              cpu: "250m"
            limits:
              memory: "150Mi"
          startupProbe:
            initialDelaySeconds: 3
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 2
            httpGet:
              path: /
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: demo
spec:
  selector:
    app: demo
  ports:
    - targetPort: 80
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: demo
  name: demo
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - demo.porridgewithprotein.xyz
      secretName: demo-porridgewithprotein
  rules:
    - host: demo.porridgewithprotein.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo
                port:
                  number: 80
