name: CD react.porridgewithprotein.xyz

on:
  push:
    branches: [demo]

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Todo.Web/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:latest

  deploy_to_k8s:
    runs-on: ubuntu-latest
    needs: push_to_registry

    steps:
      - uses: actions/checkout@v2

      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            kube/demo.yml
          images: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}
